---
version: '2'
services:
  elasticsearch:
    image: elasticsearch:5
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data:rw
  kibana:
    build: kibana
    ports:
      - 5601:5601
    links:
      - elasticsearch
  logstash:
    build: logstash
    ports:
      - 9600:9600
    links:
      - elasticsearch
